### ISSUE TITLE
Cron issues

### ISSUE THREAD

**Issue by Teglgaard** [brada1703/Laravel8-AWS#1]
Hi and thank you for such a great tutuorial. 

I have followed your tutorial but the cron jobs are not being run. I have deployed the cron config file that you have made but without any success. Is there a change when running it on an Amazon Linux 2 Instance?

It would be great to know if it works for you.

/Anders

**Comment by Teglgaard** [comment]
@brada1703 
When looking into the CRON log

I get entries like this 
CROND[26291]: (root) CMD (. /opt/elasticbeanstalk/support/envvars && /usr/bin/php /var/www/html/artisan schedule:run 1>> /dev/null 2>&1)

**Comment by Teglgaard** [comment]
I ended up using another solution which works like a charm.

Remember to adjust the own needs: https://github.com/AWSomeTech/aws-eb-laravel

**Comment by najathi** [comment]
I got same error. do you have any solution?

**Comment by Teglgaard** [comment]
@najathi the solution is already posted
